# Overrides for staging 'codeorigin' hosts
# - /hierdata/common.yaml
# - /hierdata/roles/codeorigin.yaml
# - /hierdata/environments/staging/common.yaml
# - /hierdata/environments/staging/roles/codeorigin.yaml [THIS FILE]

profile::codeorigin::vhost_hostnames:
  - code2.jquery.com
  - "%{::facts.networking.fqdn}"

profile::puppet::agent::puppet_server: puppet-05.ops.jquery.net
