# Overrides for production 'miscweb' hosts
# - /hierdata/common.yaml
# - /hierdata/roles/miscweb.yaml [unused]
# - /hierdata/environments/production/common.yaml
# - /hierdata/environments/production/roles/miscweb.yaml [THIS FILE]

profile::certbot::certificates:
  miscweb-fqdn:
    domains:
      - "%{::facts.networking.fqdn}"
  miscweb-sites:
    domains:
      - docs.jquery.com
      - podcast.jquery.com
      - demos.jquerymobile.com
      - themeroller.jquerymobile.com
      - bugs.jquery.com
      - bugs.jqueryui.com
      - plugins.jquery.com
profile::notifier::tls_key_name: miscweb-fqdn
profile::miscweb::fqdn_certificate: miscweb-fqdn
profile::miscweb::default_certificate: miscweb-sites

profile::miscweb::sites:
  demos.jquerymobile.com:
    repository:
      name: jquery/demos.jquerymobile.com
      branch: main
    allow_php: true
    # script-src: unsafe-eval for syntax highlighting on all pages
    # script-src: unsafe-inline for popup page
    # script-src: load scripts from code.jquery.com
    # script-src: load scripts from maps.google.com
    # script-src: load scripts from cdn.jsdelivr.net
    # script-src: load script from gd.geobytes.com
    # connect-src: connect to maps.googleapis.com
    # connect-src: fetch fonts from fonts.googleapis.com
    # img-src: data: for inline SVGs
    # img-src: load images from code.jquery.com
    # img-src: load images from maps.gstatic.com
    # img-src: load images from maps.google.com
    # style-src|font-src: load fonts from Google Fonts
    # style-src: load styles from code.jquery.com
    # style-src: load styles from cdn.jsdelivr.net
    # style-src: unsafe-inline for supports tests in
    #   jQuery 1.7.3 and jQuery Mobile 1.3.0
    csp_header: default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' gd.geobytes.com code.jquery.com maps.google.com cdn.jsdelivr.net; connect-src 'self' maps.googleapis.com fonts.googleapis.com; img-src 'self' code.jquery.com maps.gstatic.com maps.google.com data:; style-src 'self' 'unsafe-inline' code.jquery.com fonts.googleapis.com cdn.jsdelivr.net; font-src 'self' fonts.gstatic.com; report-uri https://csp-report-api.openjs-foundation.workers.dev/; report-to csp-endpoint
  podcast.jquery.com:
    repository:
      name: jquery/podcast.jquery.com
      branch: main
    webroot: /build_production
    notifier: true
    extra_config: |
      # http://blog.jquery.com/2010/09/04/jquery-podcast-has-a-new-home/
      rewrite ^/contact-us/$ /about/ permanent;
      # Compatibility with http://feeds.feedburner.com/jQueryPodcastShowNotes
      rewrite ^/feed/?$ /feed/jQueryPodcastShowNotes.xml permanent;
      rewrite ^/2010/10/22/ben-nadel/?$ /2010/10/22/episode-37-ben-nadel/ permanent;
      rewrite ^/2010/11/10/jquery-mobile/?$ /2010/11/10/episode-39-jquery-mobile/ permanent;
  themeroller.jquerymobile.com:
    repository:
      name: jquery/themeroller.jquerymobile.com
      branch: main
    allow_php: true
    extra_config: |
      location ~ ^/zips/(?<name>.*)\.zip {
        alias /var/cache/themeroller-zip/$name.zip;
      }
    php_env:
      THEMEROLLER_ZIPDIR: /var/cache/themeroller-zip
    # style-src: unsafe-inline for inline styles
    # script-src: unsafe-inline for inline scripts
    # img-src: data: for inline images
    csp_header: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; report-uri https://csp-report-api.openjs-foundation.workers.dev/; report-to csp-endpoint
  bugs.jquery.com:
    repository:
      name: jquery/bugs.jquery.com
      branch: gh-pages
    notifier: true
  bugs.jqueryui.com:
    repository:
      name: jquery/bugs.jqueryui.com
      branch: gh-pages
    notifier: true
  plugins.jquery.com:
    repository:
      name: jquery/plugins.jquery.com-static
      branch: gh-pages
    notifier: true

# Let's Encrypt allows 50 domains per cert.
#
# Once a cert spans 50 domains, assign further domains to a new group.
# Certs are made automatically from this map, so to create a new group
# simply start referring to a new group name here.
#
# Full groups: miscweb-redirects-a (48)
#
# Group for next domain: miscweb-redirects-b
profile::miscweb::redirects:
  # css-chassis.com
  css-chassis.com:
    target: https://github.com/jquery/css-chassis
    mode: root
    certificate: miscweb-redirects-a
  perf.css-chassis.com:
    target: https://github.com/jquery/css-chassis
    mode: root
    certificate: miscweb-redirects-a
  view.css-chassis.com:
    target: https://github.com/jquery/css-chassis
    mode: root
    certificate: miscweb-redirects-a
  www.css-chassis.com:
    target: https://github.com/jquery/css-chassis
    mode: root
    certificate: miscweb-redirects-a
  # css-chassis.org
  css-chassis.org:
    target: https://github.com/jquery/css-chassis
    mode: root
    certificate: miscweb-redirects-a
  www.css-chassis.org:
    target: https://github.com/jquery/css-chassis
    mode: root
    certificate: miscweb-redirects-a
  # globalizejs.com
  globalizejs.com:
    target: https://github.com/globalizejs/globalize
    mode: root
    certificate: miscweb-redirects-a
  www.globalizejs.com:
    target: https://github.com/globalizejs/globalize
    mode: root
    certificate: miscweb-redirects-a
  # js.foundation
  js.foundation:
    target: https://openjsf.org
    mode: root
    certificate: miscweb-redirects-a
  www.js.foundation:
    target: https://openjsf.org
    mode: root
    certificate: miscweb-redirects-a
  cla.js.foundation:
    target: https://cla.openjsf.org
    mode: root
    certificate: miscweb-redirects-a
  # jquery.com
  brand.jquery.com:
    target: https://brand.jquery.org
    mode: prefix
    certificate: miscweb-redirects-a
  contribute.jquery.com:
    target: https://contribute.jquery.org
    mode: prefix
    certificate: miscweb-redirects-a
  dev.jquery.com:
    target: https://bugs.jquery.com
    mode: prefix
    certificate: miscweb-redirects-a
  download.jquery.com:
    target: https://jquery.com/download/
    mode: root
    certificate: miscweb-redirects-a
  download.jquerymobile.com:
    target: https://jquerymobile.com/download/
    mode: root
    certificate: miscweb-redirects-a
  events.jquery.com:
    target: https://openjsf.org/events
    mode: root
    certificate: miscweb-redirects-a
  irc.jquery.com:
    target: https://irc.jquery.org/
    mode: root
    certificate: miscweb-redirects-a
  m.jquery.com:
    target: https://jquery.com
    mode: root
    certificate: miscweb-redirects-a
  meetups.jquery.com:
    target: https://jquery.com/meetups/
    mode: root
    certificate: miscweb-redirects-a
  try.jquery.com:
    # "Try jQuery" is no more.
    # https://blog.jquery.com/2013/02/22/try-jquery-interactive-course/
    target: https://learn.jquery.com/
    mode: root
    certificate: miscweb-redirects-a
  ui.jquery.com:
    target: https://jqueryui.com
    mode: prefix
    certificate: miscweb-redirects-a
  view.jquery.com:
    # Gitview was a file browser for release artefacts, superseded by the releases docsite.
    # https://github.com/jquery/infrastructure/issues/503
    target: https://releases.jquery.com/jquery/
    mode: root
    certificate: miscweb-redirects-a
  www.jquery.com:
    target: https://jquery.com
    mode: prefix
    certificate: miscweb-redirects-a
  # jqueryui.com
  dev.jqueryui.com:
    target: https://bugs.jqueryui.com
    mode: prefix
    certificate: miscweb-redirects-a
  learn.jqueryui.com:
    target: https://learn.jquery.com/jquery-ui/
    mode: root
    certificate: miscweb-redirects-a
  view.jqueryui.com:
    target: https://releases.jquery.com/ui/
    mode: root
    certificate: miscweb-redirects-a
  wiki.jqueryui.com:
    target: https://jqueryui.pbworks.com
    mode: prefix
    certificate: miscweb-redirects-a
  www.jqueryui.com:
    target: https://jqueryui.com
    mode: prefix
    certificate: miscweb-redirects-a
  # jquerymobile.com
  jquerymobile.net:
    target: https://jquerymobile.com
    mode: root
    certificate: miscweb-redirects-a
  jquerymobile.org:
    target: https://jquerymobile.com
    mode: root
    certificate: miscweb-redirects-a
  view.jquerymobile.com:
    target: https://releases.jquery.com/mobile/
    mode: root
    certificate: miscweb-redirects-a
  www.jquerymobile.com:
    target: https://jquerymobile.com
    mode: prefix
    certificate: miscweb-redirects-a
  # jquery.org
  events.jquery.org:
    target: https://openjsf.org/events
    mode: root
    certificate: miscweb-redirects-a
  m.jquery.org:
    target: https://jquery.com
    mode: root
    certificate: miscweb-redirects-a
  meetups.jquery.org:
    target: https://jquery.com/meetups/
    mode: root
    certificate: miscweb-redirects-a
  swarm.jquery.com:
    target: https://github.com/jquery/testswarm
    mode: root
    certificate: miscweb-redirects-a
  swarm.jquery.org:
    target: https://github.com/jquery/testswarm
    mode: root
    certificate: miscweb-redirects-a
  view.jquery.org:
    target: https://releases.jquery.com/jquery/
    mode: root
    certificate: miscweb-redirects-a
  www.jquery.org:
    target: https://jquery.org
    mode: prefix
    certificate: miscweb-redirects-a
  # ThemeRoller
  themeroller.net:
    target: https://jqueryui.com/themeroller/
    mode: root
    certificate: miscweb-redirects-a
  www.themeroller.net:
    target: https://jqueryui.com/themeroller/
    mode: root
    certificate: miscweb-redirects-a
  themeroller.org:
    target: https://jqueryui.com/themeroller/
    mode: root
    certificate: miscweb-redirects-a
  www.themeroller.org:
    target: https://jqueryui.com/themeroller/
    mode: root
    certificate: miscweb-redirects-a
  # QUnit
  api.qunitjs.com:
    target: https://qunitjs.com
    mode: prefix
    certificate: miscweb-redirects-a
  www.qunitjs.com:
    target: https://qunitjs.com
    mode: prefix
    certificate: miscweb-redirects-a
  api.qunitjs.org:
    target: https://qunitjs.com
    mode: prefix
    certificate: miscweb-redirects-a
  qunitjs.org:
    target: https://qunitjs.com
    mode: prefix
    certificate: miscweb-redirects-a
