profile::certbot::certificates:
  miscweb:
    domains:
      - "%{::facts.fqdn}"
      - docs.jquery.com
      - podcast.jquery.com
      - demos.jquerymobile.com
      - themeroller.jquerymobile.com
      - bugs.jquery.com
      - bugs.jqueryui.com
      - plugins.jquery.com
profile::notifier::tls_key_name: miscweb
profile::miscweb::default_certificate: miscweb

profile::miscweb::sites:
  demos.jquerymobile.com:
    repository:
      name: jquery/demos.jquerymobile.com
      branch: main
    allow_php: true
  podcast.jquery.com:
    repository:
      name: jquery/podcast.jquery.com
      branch: main
    webroot: /build_production
    notifier: true
    extra_config: |
      # http://blog.jquery.com/2010/09/04/jquery-podcast-has-a-new-home/
      rewrite ^/contact-us/$ /about/ permanent;
      # Compatibility with http://feeds.feedburner.com/jQueryPodcastShowNotes
      rewrite ^/feed/?$ /feed/jQueryPodcastShowNotes.xml permanent;
      rewrite ^/2010/10/22/ben-nadel/$ /2010/10/22/episode-37-ben-nadel/ permanent;
      rewrite ^/2010/11/10/jquery-mobile/$ /2010/11/10/episode-39-jquery-mobile/ permanent;
  themeroller.jquerymobile.com:
    repository:
      name: jquery/themeroller.jquerymobile.com
      branch: main
    allow_php: true
    extra_config: |
      location ~ ^/zips/(?<name>.*)\.zip {
        alias /var/cache/themeroller-zip/$name.zip;
      }
    php_env:
      THEMEROLLER_ZIPDIR: /var/cache/themeroller-zip
  bugs.jquery.com:
    repository:
      name: jquery/bugs.jquery.com
      branch: gh-pages
    notifier: true
  bugs.jqueryui.com:
    repository:
      name: jquery/bugs.jqueryui.com
      branch: gh-pages
    notifier: true
  plugins.jquery.com:
    repository:
      name: jquery/plugins.jquery.com-static
      branch: gh-pages
    notifier: true

profile::miscweb::redirects:
  # css-chassis.com
  css-chassis.com:
    target: https://github.com/jquery/css-chassis
    mode: root
    certificate: miscweb-a
  perf.css-chassis.com:
    target: https://github.com/jquery/css-chassis
    mode: root
    certificate: miscweb-a
  view.css-chassis.com:
    target: https://github.com/jquery/css-chassis
    mode: root
    certificate: miscweb-a
  www.css-chassis.com:
    target: https://github.com/jquery/css-chassis
    mode: root
    certificate: miscweb-a
  # css-chassis.org
  css-chassis.org:
    target: https://github.com/jquery/css-chassis
    mode: root
    certificate: miscweb-a
  www.css-chassis.org:
    target: https://github.com/jquery/css-chassis
    mode: root
    certificate: miscweb-a
  # globalizejs.com
  globalizejs.com:
    target: https://github.com/globalizejs/globalize
    mode: root
    certificate: miscweb-a
  www.globalizejs.com:
    target: https://github.com/globalizejs/globalize
    mode: root
    certificate: miscweb-a
  # js.foundation
  js.foundation:
    target: https://openjsf.org
    mode: root
    certificate: miscweb-a
  www.js.foundation:
    target: https://openjsf.org
    mode: root
    certificate: miscweb-a
  cla.js.foundation:
    target: https://cla.openjsf.org
    mode: root
    certificate: miscweb-a
  # jquery.com
  brand.jquery.com:
    target: https://brand.jquery.org
    mode: prefix
    certificate: miscweb-a
  contribute.jquery.com:
    target: https://contribute.jquery.org
    mode: prefix
    certificate: miscweb-a
  dev.jquery.com:
    target: https://bugs.jquery.com
    mode: prefix
    certificate: miscweb-a
  download.jquery.com:
    target: https://jquery.com/download/
    mode: root
    certificate: miscweb-a
  download.jquerymobile.com:
    target: https://jquerymobile.com/download/
    mode: root
    certificate: miscweb-a
  events.jquery.com:
    target: https://openjsf.org/events
    mode: root
    certificate: miscweb-a
  irc.jquery.com:
    target: https://irc.jquery.org/
    mode: root
    certificate: miscweb-a
  m.jquery.com:
    target: https://jquery.com
    mode: root
    certificate: miscweb-a
  meetups.jquery.com:
    target: https://jquery.com/meetups/
    mode: root
    certificate: miscweb-a
  try.jquery.com:
    # "Try jQuery" is no more.
    # https://blog.jquery.com/2013/02/22/try-jquery-interactive-course/
    target: https://learn.jquery.com/
    mode: root
    certificate: miscweb-a
  swarm.jquery.com:
    target: https://swarm.jquery.org
    mode: prefix
    certificate: miscweb-a
  ui.jquery.com:
    target: https://jqueryui.com
    mode: prefix
    certificate: miscweb-a
  view.jquery.com:
    # Gitview was a file browser for release artefacts, superseded by the releases docsite.
    # https://github.com/jquery/infrastructure/issues/503
    target: https://releases.jquery.com/jquery/
    mode: root
    certificate: miscweb-a
  www.jquery.com:
    target: https://jquery.com
    mode: prefix
    certificate: miscweb-a
  # jqueryui.com
  dev.jqueryui.com:
    target: https://bugs.jqueryui.com
    mode: prefix
    certificate: miscweb-a
  learn.jqueryui.com:
    target: https://learn.jquery.com/jquery-ui/
    mode: root
    certificate: miscweb-a
  view.jqueryui.com:
    target: https://releases.jquery.com/ui/
    mode: root
    certificate: miscweb-a
  wiki.jqueryui.com:
    target: https://jqueryui.pbworks.com
    mode: prefix
    certificate: miscweb-a
  www.jqueryui.com:
    target: https://jqueryui.com
    mode: prefix
    certificate: miscweb-a
  # jquerymobile.com
  jquerymobile.net:
    target: https://jquerymobile.com
    mode: root
    certificate: miscweb-a
  jquerymobile.org:
    target: https://jquerymobile.com
    mode: root
    certificate: miscweb-a
  view.jquerymobile.com:
    target: https://releases.jquery.com/mobile/
    mode: root
    certificate: miscweb-a
  www.jquerymobile.com:
    target: https://jquerymobile.com
    mode: prefix
    certificate: miscweb-a
  # jquery.org
  events.jquery.org:
    target: https://openjsf.org/events
    mode: root
    certificate: miscweb-a
  meetups.jquery.org:
    target: https://jquery.com/meetups/
    mode: root
    certificate: miscweb-a
  view.jquery.org:
    target: https://releases.jquery.com/jquery/
    mode: root
    certificate: miscweb-a
  www.jquery.org:
    target: https://jquery.org
    mode: prefix
    certificate: miscweb-a
  # ThemeRoller
  themeroller.net:
    target: https://jqueryui.com/themeroller/
    mode: root
    certificate: miscweb-a
  www.themeroller.net:
    target: https://jqueryui.com/themeroller/
    mode: root
    certificate: miscweb-a
  themeroller.org:
    target: https://jqueryui.com/themeroller/
    mode: root
    certificate: miscweb-a
  www.themeroller.org:
    target: https://jqueryui.com/themeroller/
    mode: root
    certificate: miscweb-a
  # QUnit
  api.qunitjs.com:
    target: https://qunitjs.com
    mode: prefix
    certificate: miscweb-a
