# Overrides for any 'blogs' hosts (production AND staging)
# - /hierdata/common.yaml
# - /hierdata/roles/blogs.yaml [THIS FILE]
# - /hierdata/environments/*/common.yaml
# - /hierdata/environments/*/roles/blogs.yaml [unused]

profile::certbot::certificates:
  blogs:
    domains:
      - "%{::facts.fqdn}"

profile::notifier::tls_key_name: blogs
profile::wordpress::base::default_site_cert: blogs
