# Overrides for any 'contentorigin' hosts
# - /hierdata/common.yaml
# - /hierdata/roles/contentorigin.yaml [THIS FILE]
# - /hierdata/environments/*/common.yaml
# - /hierdata/environments/*/roles/contentorigin.yaml

profile::certbot::certificates:
  contentorigin:
    domains:
      - "%{::facts.networking.fqdn}"

profile::contentorigin::tls_key_name: contentorigin
