# Overrides for any 'gruntjscom' hosts (production AND staging)
# - /hierdata/common.yaml
# - /hierdata/roles/gruntjscom.yaml [THIS FILE]
# - /hierdata/environments/*/common.yaml
# - /hierdata/environments/*/roles/gruntjscom.yaml

profile::certbot::certificates:
  gruntjscom:
    domains:
      - "%{::facts.networking.fqdn}"

profile::gruntjscom::canonical_name: gruntjs.com
profile::gruntjscom::tls_key_name: gruntjscom
profile::notifier::tls_key_name: gruntjscom
