name: CI
on:
  push:
  pull_request:

jobs:
  lint:
    # https://github.com/actions/virtual-environments/blob/ubuntu20/20220605.1/images/linux/Ubuntu2004-Readme.md
    #
    # Includes Ruby 2.7 and RubyGems 3.1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install puppet-lint
        run: |
          sudo gem install puppet-lint -v '~> 2'

      - run: make lint
