name: smoke
on:
  # Daily at 7:30 UTC. https://crontab.guru/
  schedule:
    - cron: '30 7 * * *'
  # Or manually
  workflow_dispatch:
  # Or when developing this workflow
  push:
    paths:
      - .github/workflows/smoke.yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: make test
